from .flick_cast_crew import Flick_Cast_Crew
from .flick_genre import Flick_Genre
from .flick_mood import Flick_Mood
from .flick_recommended_by import Flick_Recommended_By
from .flick import Flick
from .friend import Friend
from .mood import Mood
from .genre import Genre
from .user_flick import User_Flick
from .user_genre import User_Genre
from .user import User
from .friend_request import Friend_Request
