# Generated by Django 4.1.5 on 2023-01-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('watched', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=1000)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.genre')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Flick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flick_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.flick')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Flick_Recommended_By',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_by', models.CharField(max_length=100)),
                ('flick_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.flick')),
            ],
        ),
        migrations.CreateModel(
            name='Flick_Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flick_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.flick')),
                ('mood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.mood')),
            ],
        ),
        migrations.CreateModel(
            name='Flick_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flick_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.flick')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Flick_Cast_Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_crew', models.CharField(max_length=100)),
                ('flick_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poppedapi.flick')),
            ],
        ),
    ]
