# Generated by Django 4.1.5 on 2023-01-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poppedapi', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
