# Generated by Django 4.1.5 on 2023-01-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poppedapi', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
