# Generated by Django 4.1.5 on 2023-01-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poppedapi', '0006_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flick_cast_crew',
            old_name='flick_id',
            new_name='flick',
        ),
        migrations.RenameField(
            model_name='flick_genre',
            old_name='flick_id',
            new_name='flick',
        ),
        migrations.RenameField(
            model_name='flick_genre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='flick_mood',
            old_name='flick_id',
            new_name='flick',
        ),
        migrations.RenameField(
            model_name='flick_mood',
            old_name='mood_id',
            new_name='mood',
        ),
        migrations.RenameField(
            model_name='flick_recommended_by',
            old_name='flick_id',
            new_name='flick',
        ),
        migrations.RenameField(
            model_name='friend_request',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_flick',
            old_name='flick_id',
            new_name='flick',
        ),
        migrations.RenameField(
            model_name='user_flick',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_genre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='user_genre',
            old_name='user_id',
            new_name='user',
        ),
    ]
