# Generated by Django 4.1.5 on 2023-01-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poppedapi', '0007_rename_flick_id_flick_cast_crew_flick_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_genre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='user_genre',
            old_name='user',
            new_name='user_id',
        ),
    ]
